# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTesteAutomatizado01():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testeAutomatizado01(self):
    # abre o navegador e insere a URL base
    self.driver.get("https://www.kabum.com.br/")
    # seta tamanho da pagina
    self.driver.set_window_size(1874, 1096)
    # clique na barra de busca
    self.driver.find_element(By.CSS_SELECTOR, ".sprocura").click()
    # digita a string de busca
    self.driver.find_element(By.CSS_SELECTOR, ".sprocura").send_keys("placa de video")
    # clique no botão para executar a busca
    self.driver.find_element(By.ID, "bt-busca").click()
    # validação de busca
    assert self.driver.find_element(By.LINK_TEXT, "Placa de Vídeo ZOTAC GAMING GeForce RTX 3060 Twin Edge OC, 15 Gbps, 12GB, GDDR6, Ray Tracing - ZT-A30600H-10M").text == "Placa de Vídeo ZOTAC GAMING GeForce RTX 3060 Twin Edge OC, 15 Gbps, 12GB, GDDR6, Ray Tracing - ZT-A30600H-10M"
    # clique para adicionar o item ao carrinho
    self.driver.find_element(By.CSS_SELECTOR, ".sc-fzqARJ:nth-child(3) .sc-AxhCb > img").click()
    # clique no botão que vai ao carrinho
    self.driver.find_element(By.LINK_TEXT, "IR PARA O CARRINHO").click()
    # validação do item no carrinho
    assert self.driver.find_element(By.CSS_SELECTOR, "h4").text == "Placa de Vídeo ZOTAC GAMING GeForce RTX 3060 Twin Edge OC, 15 Gbps, 12GB, GDDR6, Ray Tracing - ZT-A30600H-10M"
    # fecha o navegador
    self.driver.close()
  
